### PR TITLE
Add kab language

### PR DESCRIPTION
**Pull request by belkacem77**
Add kab language as it reached 76% on LibreOffice Master - UI

### CODE REVIEW

**Comment by fitojb** [comment]
@cloph Can you do this change for Muḥend?

**Comment by fitojb** [comment]
@belkacem77 We use [Gerrit](https://wiki.documentfoundation.org/Development/gerrit) for development; this is a mirror to provide people an alternative place to pull changes from. Of course, this mirror is badly configured; it should not allow people to make pull requests.

The change you’re requesting should look like [this patch](https://cgit.freedesktop.org/libreoffice/core/commit/?id=f8fb04d0af7b1d21b8638e92922d0965e507c5d9).

**Comment by belkacem77** [comment]
@fitojb thanks for explanation. I'll close this PR

**Comment by fitojb** [comment]
Solved with commits 0b7ab07611ddaafe25e9e1914a49be2afe68ada9 and LibreOffice/translations@1ed5e59b7cf6a3453cf2ca2fe0eebf45b75b2e1d. Thanks @belkacem77 and @cloph!

**Pull request closed without merging**
